name: Test Docker image

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Build the Docker image
        run: |
          docker run -i $(docker build -q canary-alpine) /bin/sh -c "node --version && npm --version && bun --version"
          docker run -i $(docker build -q alpine) /bin/sh -c "node --version && npm --version && bun --version "

  auto-merge:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Automatically merge dependabot upgrades
        uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
          target: minor
